sudo: required
services:
  - docker

before_install:
  - docker build -t kervin102/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kervin102/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-921943203968"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KET"
  
